# Generated by Django 2.2.7 on 2024-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20240225_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Figure'),
        ),
    ]
